"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:blue)\
$directory\
[](fg:blue bg:dark_blue)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:dark_blue bg:darker_blue)\
$jobs\
[](fg:darker_blue bg:deep_blue)\
$cmd_duration\
[](fg:deep_blue)\
$fill\
[](fg:darker_blue)\
$time\
[](fg:darker_blue)\
$line_break\
$character\
"""

# Define the palette
palette = "tokyo_night"

[palettes.tokyo_night]
text = "#e5e9f0"
blue = "#769ff0"
sky = "#7aa2f7"
cyan = "#7dcfff"
dark_blue = "#394260"
darker_blue = "#212736"
deep_blue = "#1d2230"
muted = "#a0a9cb"
purple = "#c792ea"
red = "#ff5555"
salmon = "#f07178"
yellow = "#f2c96d"
green = "#8bd49c"

[directory]
style = "fg:text bg:blue"
format = "[$path ]($style)[$read_only]($read_only_style)"
read_only = ""
read_only_style = 'fg:red bg:blue'
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:blue bg:dark_blue)'

[git_commit]
style = "bg:dark_blue"
tag_disabled = false
format = '[\($hash$tag\)](fg:blue bg:dark_blue)'

[git_state]
style = "bg:dark_blue"
format = '[ \($state( $progress_current/$progress_total)\) ](fg:yellow bg:dark_blue)'
disabled = false

[git_status]
ahead = '[⇡${count}](fg:green bg:dark_blue)'
behind = '[⇣${count}](fg:green bg:dark_blue)'
diverged = '[⇡${ahead_count}⇣${behind_count}](fg:green bg:dark_blue)'

conflicted = '[~$count](fg:salmon bg:dark_blue)'
untracked = '[?$count](fg:sky bg:dark_blue)'
stashed = '[*$count](fg:purple bg:dark_blue)'
modified = '[!$count](fg:yellow bg:dark_blue)'
staged = '[+$count](fg:green bg:dark_blue)'
renamed = '[»$count](fg:sky bg:dark_blue)'
deleted = '[✘$count](fg:salmon bg:dark_blue)'
style = "bg:dark_blue"

format = '[($conflicted )($stashed )($deleted )($renamed )($modified )($staged )($untracked )$ahead_behind]($style)'

[jobs]
style = "fg:cyan bg:darker_blue"
format = '[ $symbol$number]($style)'

[cmd_duration]
format = '[$duration](fg:text bg:deep_blue)'

[time]
disabled = false
time_format = "%r" # 12-hour with seconds and AM/PM
format = '[  $time ](fg:muted bg:darker_blue)'
